spring.application.name=ms-cursos
server.port=8002

spring.datasource.url=jdbc:postgresql://localhost/ms-cursos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug

#spring.jpa.properties.hibernate.jdbc.lo